### ISSUE TITLE
[...] drop React Native 0.59 support

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#132]
to 0.60/+

as proposed in PR #130

this should resolve an issue with tvOS as discussed in PR #130 (and PR #126)

with some blocking TODO items:

- [ ] I think the `pod install` step documented in #99 should be automated, just like recent versions of React Native CLI seem to automate this step
- [ ] document how to go back to react-native@0.59 for Windows support
- [ ] document how to go back to react-native@0.59 for Expo support
- [ ] resolve TODO items in PR #130
- [ ] Android view issue discussed in #29 (a proposed solution should be coming soon)
