### ISSUE TITLE
[...] followup to android build.gradle template setup updates

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#143]
some followup items to PR #135:

- [ ] update the generated `.npmignore` and the `files` entry as proposed by PRs linked by <https://github.com/react-native-community/discussions-and-proposals/issues/151#issuecomment-532781905> & <https://github.com/facebook/react-native/pull/25569>: 
  - [react-native-community/react-native-localize#69](https://github.com/react-native-community/react-native-localize/pull/69)
  - [react-native-community/react-native-share#588](https://github.com/react-native-community/react-native-share/pull/588)
  - [react-native-community/async-storage#209](https://github.com/react-native-community/async-storage/pull/209)
  - [FormidableLabs/react-native-app-auth#384](https://github.com/FormidableLabs/react-native-app-auth/pull/384)
- [ ] move some definitions and imports like I proposed in PRs #140, #141, and #142
- [ ] add some more comments like I suggested in my comments on PR #140
- [ ] raise a new issue that describes the solution from <https://github.com/react-native-community/discussions-and-proposals/issues/151#issuecomment-532781905> & <https://github.com/facebook/react-native/pull/25569>, without all of the noise

/cc @friederbluemle @SaeedZhiany
