### ISSUE TITLE
Fix React Native 0.61 support

### ISSUE THREAD

**Issue by brodybits** [brodybits/create-react-native-module#93]
- [ ] _test generated module & generated view module with example on Android & iOS on React Native ~~0.61-rc~~ **0.61.1(+)**_
- [ ] _update documentation_
- [ ] _Check (again) for Gradle updates from 0.61-stable_
- [ ] _fix Android view (#29)_
- [ ] _fix generated iOS example (#99)_
- [ ] _update default example react-native version, likely to react-native@latest (this is already part of proposal in PR #130)_
- [ ] _consider dropping react-native 0.59 support (see issue #132 & my proposal in PR #130)_
- [ ] _consider option to configure minimum react-native version (as proposed in PR #130)_
- [ ] _Android build.gradle updates from 0.61-stable (PR #107)_

**Comment by davidpfahler** [comment]
So just to clarify: `create-react-native-module` does not work with latest `react-native`? I tried to create a Native Module with it following the [official](https://facebook.github.io/react-native/docs/native-modules-setup) [guides](https://facebook.github.io/react-native/docs/native-modules-ios) and get the following errors when `react-native run-ios`:

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-core-ml (to unlink run: "react-native unlink react-native-core-ml")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
error Could not find the following native modules: react-native-core-ml. Did you forget to run "pod install" ?
```

When I then `cd ios; pod install`:

```
Detected React Native module pod for react-native-core-ml
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "react-native-core-ml":
  In Podfile:
    react-native-core-ml (from `../node_modules/react-native-core-ml`)

Specs satisfying the `react-native-core-ml (from `../node_modules/react-native-core-ml`)` dependency were found, but they required a higher minimum deployment target.
```

In the simulator:

```
error: bundling failed: Error: Unable to resolve module `warnOnce` from `node_modules/react-native-core-ml/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: warnOnce could not be found within the project.
```

Is this expected behavior at this point in time?

**Comment by zivchen** [comment]
+1
Same error
"react-native": "0.61.5"

**Comment by PosSoolutions** [comment]
+1 
Same error
"react-native": "0.61.5"
